<?php

namespace AdminBundle\Repository;

/**
 * AboutusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AboutusRepository extends \Doctrine\ORM\EntityRepository
{
}
