<?php

namespace AdminBundle\Repository;

/**
 * ContactusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactusRepository extends \Doctrine\ORM\EntityRepository
{
}
