<?php

namespace AdminBundle\Repository;

/**
 * DMCARepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DMCARepository extends \Doctrine\ORM\EntityRepository
{
}
