<?php

namespace AdminBundle\Repository;

/**
 * PrivacyPolicyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrivacyPolicyRepository extends \Doctrine\ORM\EntityRepository
{
}
