contactus_index:
    path:     /
    defaults: { _controller: "AdminBundle:Contactus:index" }
    methods:  GET

contactus_show:
    path:     /{id}/show
    defaults: { _controller: "AdminBundle:Contactus:show" }
    methods:  GET

contactus_new:
    path:     /new
    defaults: { _controller: "AdminBundle:Contactus:new" }
    methods:  [GET, POST]

contactus_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:Contactus:edit" }
    methods:  [GET, POST]

contactus_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:Contactus:delete" }
    methods:  DELETE
