dmca_index:
    path:     /
    defaults: { _controller: "AdminBundle:DMCA:index" }
    methods:  GET

dmca_show:
    path:     /{id}/show
    defaults: { _controller: "AdminBundle:DMCA:show" }
    methods:  GET

dmca_new:
    path:     /new
    defaults: { _controller: "AdminBundle:DMCA:new" }
    methods:  [GET, POST]

dmca_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:DMCA:edit" }
    methods:  [GET, POST]

dmca_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:DMCA:delete" }
    methods:  DELETE
